
background_opacity 0.65
background            #264c55
foreground            #e2e8f0
selection_background  #35636e
selection_foreground  #ffffff
url_color             #4f8996

color0 #1d3a41
color8 #2d545e

color1 #f87171
color9 #ef4444

color2 #4ade80
color10 #22c55e

color3 #fbbf24
color11 #f59e0b

color4 #4f8996
color12 #60a5fa

color5 #c084fc
color13 #a855f7

color6 #35636e
color14 #2ec4b6

color7 #94a3b8
color15 #ffffff

window_padding_width 15
hide_window_decorations yes

# KITTY_FONTS
font_family      family="Adwaita Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        20.0
